/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R404RouteImport } from './routes/404'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as RobotsRouteImport } from './routes/robots'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as TermsOfServicesRouteImport } from './routes/terms-of-services'
import { Route as WorkRouteImport } from './routes/work'
import { Route as ProductsPharmacyPosRouteImport } from './routes/products/pharmacy-pos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsRoute = RobotsRouteImport.update({
  id: '/robots',
  path: '/robots',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServicesRoute = TermsOfServicesRouteImport.update({
  id: '/terms-of-services',
  path: '/terms-of-services',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsPharmacyPosRoute = ProductsPharmacyPosRouteImport.update({
  id: '/products/pharmacy-pos',
  path: '/products/pharmacy-pos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/robots': typeof RobotsRoute
  '/sitemap': typeof SitemapRoute
  '/terms-of-services': typeof TermsOfServicesRoute
  '/work': typeof WorkRoute
  '/products/pharmacy-pos': typeof ProductsPharmacyPosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/robots': typeof RobotsRoute
  '/sitemap': typeof SitemapRoute
  '/terms-of-services': typeof TermsOfServicesRoute
  '/work': typeof WorkRoute
  '/products/pharmacy-pos': typeof ProductsPharmacyPosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/robots': typeof RobotsRoute
  '/sitemap': typeof SitemapRoute
  '/terms-of-services': typeof TermsOfServicesRoute
  '/work': typeof WorkRoute
  '/products/pharmacy-pos': typeof ProductsPharmacyPosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/about'
    | '/contact'
    | '/privacy-policy'
    | '/robots'
    | '/sitemap'
    | '/terms-of-services'
    | '/work'
    | '/products/pharmacy-pos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/about'
    | '/contact'
    | '/privacy-policy'
    | '/robots'
    | '/sitemap'
    | '/terms-of-services'
    | '/work'
    | '/products/pharmacy-pos'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/about'
    | '/contact'
    | '/privacy-policy'
    | '/robots'
    | '/sitemap'
    | '/terms-of-services'
    | '/work'
    | '/products/pharmacy-pos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RobotsRoute: typeof RobotsRoute
  SitemapRoute: typeof SitemapRoute
  TermsOfServicesRoute: typeof TermsOfServicesRoute
  WorkRoute: typeof WorkRoute
  ProductsPharmacyPosRoute: typeof ProductsPharmacyPosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots': {
      id: '/robots'
      path: '/robots'
      fullPath: '/robots'
      preLoaderRoute: typeof RobotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-services': {
      id: '/terms-of-services'
      path: '/terms-of-services'
      fullPath: '/terms-of-services'
      preLoaderRoute: typeof TermsOfServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/pharmacy-pos': {
      id: '/products/pharmacy-pos'
      path: '/products/pharmacy-pos'
      fullPath: '/products/pharmacy-pos'
      preLoaderRoute: typeof ProductsPharmacyPosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RobotsRoute: RobotsRoute,
  SitemapRoute: SitemapRoute,
  TermsOfServicesRoute: TermsOfServicesRoute,
  WorkRoute: WorkRoute,
  ProductsPharmacyPosRoute: ProductsPharmacyPosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
